### ISSUE TITLE
Cassandra sink does not work in Standalone mode

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.cassandra#4]
This applies to version 2.0 of the toolkit, which requires application configurations to provide connection parameters.

 The other downside about only using application configuration is that running the operator in standalone mode does not seem to work, which would make sense, because all the connection information is stored in the domain or instance. 
When I submit the job in distributed mode, everything works fine, but in standalone mode I get this exception:

09 Jan 2017 19:03:27.464 [8115] ERROR #splapptrc,J[0],P[0],CoolStuff,spl_javaop M[?:com.ibm.streams.operator.internal.jni.JNIBridge.<init>:-1] 
 Failed to create Cassandra client
com.datastax.driver.core.exceptions.NoHostAvailableException:  
All host(s) tried for query failed (tried: /*x.x.x.x:9042* 
 (com.datastax.driver.core.TransportException: [/x.x.x.x:9042] Cannot connect))
   
Being unable to find the application config object in standalone mode, the client defaults to an IP address that is unreachable.

**Comment by ecurtin** [comment]
This is a consequence of how Standalone mode in Streams works. The application configuration objects are stored within the Domain (or instance). When Streams is running in Standalone mode, it's not communicating with the Domain.

So yeah, it's an issue, but it's not specific to this operator. 

Perhaps in the context of this operator, the default IP could be changed or the error message made more clear?

**Comment by ecurtin** [comment]
For other users encountering this thread, the workaround is to launch on your VM in Distributed mode.

**Comment by ecurtin** [comment]
Closing this issue as this is now documented in the README. For those just now coming across this, please launch the sample project in Distributed mode or modify the code for the sample project to use JSON string arguments (see README for details) instead of config objects.
